ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    odom_frame: odom
    base_link_frame: base_link  # ou base_link selon ton robot
    world_frame: odom
    publish_tf: true
    use_sim_time: true
    odometry0: /odom
    odometry0_config: [true, true, false,
                       false, false, true,
                       false, false, false,
                       false, false, false,
                       false, false, false]